/**
 * Demo data — mirrors real Jahangir Khan TATA 1mg report.
 * Used when the backend is not reachable (demo / offline mode).
 */

export const DEMO_ANALYSIS = {
  patient: { name: "Jahangir Khan", age: 88, sex: "Male" },
  lab_name: "TATA 1mg Labs, Okhla",
  report_date: "27 Oct 2025",
  patient_id_lab: "OKH2536878",
  stats: { total: 35, abnormal: 17, critical_flags: 6, systems_reviewed: 8 },
  biomarkers: [
    { name:"Hemoglobin",           value:11.9,  unit:"g/dL",    ref_low:13.0, ref_high:17.0, status:"LOW",    group:"CBC" },
    { name:"RBC",                  value:4.45,  unit:"10⁶/μL",  ref_low:4.5,  ref_high:5.5,  status:"LOW",    group:"CBC" },
    { name:"HCT",                  value:38.0,  unit:"%",       ref_low:40,   ref_high:50,   status:"LOW",    group:"CBC" },
    { name:"MCH",                  value:26.9,  unit:"pg",      ref_low:27,   ref_high:32,   status:"LOW",    group:"CBC" },
    { name:"RDW-CV",               value:17.0,  unit:"%",       ref_low:11.5, ref_high:14,   status:"HIGH",   group:"CBC" },
    { name:"MPV",                  value:12.5,  unit:"fL",      ref_low:6.5,  ref_high:12,   status:"HIGH",   group:"CBC" },
    { name:"PDW",                  value:27.5,  unit:"fL",      ref_low:9,    ref_high:17,   status:"HIGH",   group:"CBC" },
    { name:"Platelet Count",       value:156,   unit:"10³/μL",  ref_low:150,  ref_high:410,  status:"NORMAL", group:"CBC" },
    { name:"WBC",                  value:6.98,  unit:"10³/μL",  ref_low:4,    ref_high:10,   status:"NORMAL", group:"CBC" },
    { name:"ESR",                  value:77,    unit:"mm/hr",   ref_low:0,    ref_high:30,   status:"HIGH",   group:"Inflammatory Markers" },
    { name:"CRP",                  value:8.10,  unit:"mg/L",    ref_low:0,    ref_high:3.3,  status:"HIGH",   group:"Inflammatory Markers" },
    { name:"Iron Serum",           value:54,    unit:"μg/dL",  ref_low:65,   ref_high:175,  status:"LOW",    group:"Iron Studies" },
    { name:"Transferrin Saturation",value:17.16,unit:"%",       ref_low:20,   ref_high:50,   status:"LOW",    group:"Iron Studies" },
    { name:"TIBC",                 value:314.6, unit:"μg/dL",  ref_low:250,  ref_high:460,  status:"NORMAL", group:"Iron Studies" },
    { name:"Fasting Glucose",      value:93,    unit:"mg/dL",   ref_low:70,   ref_high:99,   status:"NORMAL", group:"Diabetes Profile" },
    { name:"HbA1c",                value:5.1,   unit:"%",       ref_low:4,    ref_high:5.6,  status:"NORMAL", group:"Diabetes Profile" },
    { name:"Microalbumin",         value:62.0,  unit:"mg/L",    ref_low:0,    ref_high:29.99,status:"HIGH",   group:"Diabetes Profile" },
    { name:"UACR",                 value:69.02, unit:"mg/g",    ref_low:0,    ref_high:30,   status:"HIGH",   group:"Diabetes Profile" },
    { name:"BUN",                  value:28,    unit:"mg/dL",   ref_low:9,    ref_high:23,   status:"HIGH",   group:"Kidney Function" },
    { name:"Urea",                 value:59.92, unit:"mg/dL",   ref_low:19.3, ref_high:49.2, status:"HIGH",   group:"Kidney Function" },
    { name:"Creatinine",           value:1.30,  unit:"mg/dL",   ref_low:0.7,  ref_high:1.3,  status:"NORMAL", group:"Kidney Function" },
    { name:"Uric Acid",            value:7.7,   unit:"mg/dL",   ref_low:3.5,  ref_high:7.2,  status:"HIGH",   group:"Kidney Function" },
    { name:"Sodium",               value:145,   unit:"mEq/L",   ref_low:136,  ref_high:145,  status:"NORMAL", group:"Kidney Function" },
    { name:"Chloride",             value:108,   unit:"mmol/L",  ref_low:98,   ref_high:107,  status:"HIGH",   group:"Kidney Function" },
    { name:"Total Cholesterol",    value:167,   unit:"mg/dL",   ref_low:0,    ref_high:199,  status:"NORMAL", group:"Lipid Profile" },
    { name:"Triglycerides",        value:124,   unit:"mg/dL",   ref_low:0,    ref_high:149,  status:"NORMAL", group:"Lipid Profile" },
    { name:"HDL",                  value:40,    unit:"mg/dL",   ref_low:40,   ref_high:999,  status:"NORMAL", group:"Lipid Profile" },
    { name:"LDL",                  value:102,   unit:"mg/dL",   ref_low:0,    ref_high:99.9, status:"HIGH",   group:"Lipid Profile" },
    { name:"SGOT",                 value:29,    unit:"U/L",     ref_low:0,    ref_high:33.9, status:"NORMAL", group:"Liver Function" },
    { name:"SGPT",                 value:27,    unit:"U/L",     ref_low:10,   ref_high:49,   status:"NORMAL", group:"Liver Function" },
    { name:"ALP",                  value:123,   unit:"U/L",     ref_low:46,   ref_high:116,  status:"HIGH",   group:"Liver Function" },
    { name:"Albumin",              value:4.38,  unit:"g/dL",    ref_low:3.2,  ref_high:4.8,  status:"NORMAL", group:"Liver Function" },
    { name:"Vitamin D",            value:12.4,  unit:"ng/mL",   ref_low:30,   ref_high:100,  status:"LOW",    group:"Vitamins & Hormones" },
    { name:"Vitamin B12",          value:237,   unit:"pg/mL",   ref_low:211,  ref_high:911,  status:"NORMAL", group:"Vitamins & Hormones" },
    { name:"Folate",               value:3.57,  unit:"ng/mL",   ref_low:5.38, ref_high:99,   status:"LOW",    group:"Vitamins & Hormones" },
    { name:"TSH",                  value:7.964, unit:"uIU/mL",  ref_low:0.55, ref_high:4.78, status:"HIGH",   group:"Vitamins & Hormones" },
    { name:"Calcium",              value:9.4,   unit:"mg/dL",   ref_low:8.7,  ref_high:10.4, status:"NORMAL", group:"Vitamins & Hormones" },
  ],
  alerts: [
    { severity:"critical", title:"Subclinical Hypothyroidism", system:"Thyroid", marker:"TSH", value:7.964, unit:"uIU/mL",
      detail:"TSH 7.964 uIU/mL elevated 67% above ULN (ref 0.55–4.78). T3 & T4 remain normal. Endocrinology referral warranted — untreated hypothyroidism accelerates anaemia and elevates cardiovascular risk in elderly patients." },
    { severity:"critical", title:"Iron-Deficiency Anaemia", system:"Haematology", marker:"Hemoglobin", value:11.9, unit:"g/dL",
      detail:"Classic IDA triad: Hb 11.9 g/dL ↓, Iron 54 μg/dL ↓, Transferrin sat. 17.2% ↓, RDW-CV 17.0% ↑. Exclude occult GI blood loss before commencing iron replacement." },
    { severity:"critical", title:"Systemic Inflammation", system:"Inflammatory", marker:"ESR", value:77, unit:"mm/hr",
      detail:"ESR 77 mm/hr (2.6× ULN) + CRP 8.10 mg/L (2.5× ULN). Combined elevation demands active aetiology workup — screen for infection, autoimmune disease, and malignancy." },
    { severity:"high", title:"Microalbuminuria · Stage A2", system:"Renal", marker:"UACR", value:69.02, unit:"mg/g",
      detail:"UACR 69.02 mg/g places patient in CKD A2 category. Early renal damage and independent CVD risk marker. Confirm with two further morning specimens within 3–6 months." },
    { severity:"high", title:"Severe Vitamin D Deficiency", system:"Vitamins", marker:"Vitamin D", value:12.4, unit:"ng/mL",
      detail:"25-OH Vit D 12.4 ng/mL — severe deficiency (threshold < 20). At 88 years this dramatically elevates fracture risk. Urgent supplementation required." },
    { severity:"high", title:"Folate Deficiency", system:"Vitamins", marker:"Folate", value:3.57, unit:"ng/mL",
      detail:"Folate 3.57 ng/mL in deficient/indeterminate range (ref > 5.38). Combined with low-normal B12, raises megaloblastic anaemia risk. Folic acid supplementation indicated." },
  ],
  risk_scores: [
    { category:"Iron-Deficiency Anaemia",     score:0.84, label:"High Risk",     shap:[{feature:"Hemoglobin",impact:0.30,positive:true},{feature:"Iron Serum",impact:0.25,positive:true},{feature:"Transferrin Saturation",impact:0.18,positive:true},{feature:"RDW-CV",impact:0.11,positive:true}] },
    { category:"Systemic Inflammation",       score:0.76, label:"High Risk",     shap:[{feature:"ESR",impact:0.42,positive:true},{feature:"CRP",impact:0.38,positive:true}] },
    { category:"Thyroid Dysfunction",         score:0.89, label:"High Risk",     shap:[{feature:"TSH",impact:0.89,positive:true}] },
    { category:"Renal Involvement",           score:0.58, label:"Moderate Risk", shap:[{feature:"UACR",impact:0.38,positive:true},{feature:"BUN",impact:0.22,positive:true},{feature:"Urea",impact:0.18,positive:true}] },
    { category:"Vitamin & Folate Deficiency", score:0.72, label:"High Risk",     shap:[{feature:"Vitamin D",impact:0.40,positive:true},{feature:"Folate",impact:0.32,positive:true}] },
  ],
  system_health: [
    { name:"Haematology",  score:42, flags:3, color:"#FF4060" },
    { name:"Inflammatory", score:28, flags:2, color:"#FF4060" },
    { name:"Thyroid",      score:40, flags:1, color:"#FFB020" },
    { name:"Renal",        score:58, flags:4, color:"#FFB020" },
    { name:"Vitamins",     score:36, flags:2, color:"#FFB020" },
    { name:"Lipids",       score:74, flags:1, color:"#4D9EFF" },
    { name:"Liver",        score:80, flags:1, color:"#00D4AA" },
    { name:"Diabetes",     score:84, flags:2, color:"#00D4AA" },
  ],
  advisory: {
    summary: "Jahangir Khan (88M) presents a clinically complex multi-system picture. Priority 1 — subclinical hypothyroidism (TSH 7.964) and iron-deficiency anaemia — are both actionable. A significant inflammatory burden (ESR 77 · CRP 8.10) demands aetiology workup. Microalbuminuria (UACR 69.02) signals early renal involvement. Severe Vitamin D and folate deficiency are immediately correctable. Diabetes, lipid, and liver panels are near-normal.",
    sections: [
      { icon:"🔴", tag:"Priority 1 · Thyroid", key:"Subclinical Hypothyroidism", values:"TSH 7.964 uIU/mL — T3 & T4 normal", color:"#FF4060",
        recs:["Endocrinology referral for levothyroxine initiation assessment","Repeat TFT with Free T3 & Free T4 in 6–8 weeks to confirm trend","Note: hypothyroidism worsens anaemia, raises LDL, and impairs cognition — address concurrently"] },
      { icon:"🔴", tag:"Priority 1 · Haematology", key:"Iron-Deficiency Anaemia", values:"Hb 11.9 g/dL ↓ · Iron 54 μg/dL ↓ · Sat 17.2% ↓", color:"#FF4060",
        recs:["Ferrous sulphate 200 mg TDS with Vitamin C on empty stomach","Investigate aetiology: dietary deficiency vs occult GI blood loss","Repeat CBC + iron studies in 8 weeks; consider IV iron if oral poorly tolerated"] },
      { icon:"🟠", tag:"Priority 2 · Renal", key:"Microalbuminuria · Stage A2", values:"UACR 69.02 mg/g Cr · BUN 28 ↑ · Urea 59.92 ↑", color:"#FFB020",
        recs:["Confirm A2 category with 2 further morning specimens within 3–6 months (ADA 2024)","Target BP < 130/80 mmHg; consider ACE inhibitor or ARB if not contraindicated","Avoid NSAIDs and nephrotoxic medications; ensure adequate hydration"] },
      { icon:"🔵", tag:"Priority 3 · Vitamins", key:"Vitamin D & Folate Deficiency", values:"Vit D 12.4 ng/mL (severe) · B9 3.57 ng/mL (deficient)", color:"#4D9EFF",
        recs:["Cholecalciferol 60,000 IU weekly × 8 weeks, then 1000–2000 IU/day maintenance","Folic acid 5 mg OD × 4 months; recheck levels at completion","DEXA scan strongly recommended — severe Vit D at 88 years carries high fracture risk"] },
    ],
  },
};
